language: node_js
node_js:
  - "8.11.3"

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change

deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN
  local_dir: dist/ngTest
  on:
    branch: master